const SERVICES_DATA = [
    {
        id: 101,
        categoryId: 1,
        categoryName: "شحن التطبيقات",
        name: "تيك توك - 1000 عملة (حاجاتي)",
        price: 15.50,
        oldPrice: 18.00,
        image: "https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=500&auto=format&fit=crop&q=60",
        badge: "الأكثر طلباً",
        inputLabel: "معرّف الحساب (User ID / Username)",
        inputPlaceholder: "أدخل اسم المستخدم أو المعرف هنا...",
        deliveryTime: "فوري (1 - 5 دقائق)"
    },
    {
        id: 102,
        categoryId: 1,
        categoryName: "شحن التطبيقات",
        name: "لايكي - 500 ماسة",
        price: 9.99,
        oldPrice: 12.00,
        image: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=500&auto=format&fit=crop&q=60",
        badge: "خصم 15%",
        inputLabel: "معرّف حساب لايكي (Likee ID)",
        inputPlaceholder: "أدخل معرّف لايكي...",
        deliveryTime: "فوري"
    },
    {
        id: 201,
        categoryId: 2,
        categoryName: "شحن الألعاب",
        name: "ببجي موبايل - 660 شدة (UC)",
        price: 10.99,
        oldPrice: 13.50,
        image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=500&auto=format&fit=crop&q=60",
        badge: "شحن رسمي فوري",
        inputLabel: "معرّف اللاعب (Player ID / Player Name)",
        inputPlaceholder: "أدخل آيدي اللاعب (مثال: 5123456789)...",
        deliveryTime: "فوري تلقائي"
    },
    {
        id: 202,
        categoryId: 2,
        categoryName: "شحن الألعاب",
        name: "فري فاير - 1080 جوهرة + جوائز",
        price: 9.50,
        oldPrice: 11.00,
        image: "https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=500&auto=format&fit=crop&q=60",
        badge: "عرض حصري HAGAATY",
        inputLabel: "معرّف الحساب (UID)",
        inputPlaceholder: "أدخل UID الخاص باللعبة...",
        deliveryTime: "1 - 3 دقائق"
    },
    {
        id: 203,
        categoryId: 2,
        categoryName: "شحن الألعاب",
        name: "روبلوكس - 800 Robux",
        price: 11.99,
        oldPrice: 14.00,
        image: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=500&auto=format&fit=crop&q=60",
        badge: "تسليم تلقائي",
        inputLabel: "اسم المستخدم (Roblox Username)",
        inputPlaceholder: "أدخل اسم مستخدم روبلوكس...",
        deliveryTime: "فوري"
    },
    {
        id: 401,
        categoryId: 4,
        categoryName: "الدفع الإلكتروني",
        name: "بطاقة بايسيرا (Paysera Credit)",
        price: 25.00,
        oldPrice: 27.00,
        image: "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=500&auto=format&fit=crop&q=60",
        badge: "آمن ومعتمد",
        inputLabel: "رقم الحساب / البريد الإلكتروني",
        inputPlaceholder: "أدخل حساب بايسيرا الخاص بك...",
        deliveryTime: "5 - 15 دقيقة"
    },
    {
        id: 402,
        categoryId: 4,
        categoryName: "الدفع الإلكتروني",
        name: "رصيد بايبال (PayPal USD Direct)",
        price: 52.00,
        oldPrice: 55.00,
        image: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=500&auto=format&fit=crop&q=60",
        badge: "تحويل مباشر",
        inputLabel: "بريد PayPal الإلكتروني",
        inputPlaceholder: "name@example.com",
        deliveryTime: "فوري"
    },
    {
        id: 501,
        categoryId: 5,
        categoryName: "المتاجر الرقمية",
        name: "بطاقة أبل ستور $25 (US Gift Card)",
        price: 25.99,
        oldPrice: 28.00,
        image: "https://images.unsplash.com/photo-1512499617640-c74ae3a79d37?w=500&auto=format&fit=crop&q=60",
        badge: "كود فوري",
        inputLabel: "رقم الواتساب أو البريد لاستلام الكود",
        inputPlaceholder: "رقم الهاتف / البريد الإلكتروني...",
        deliveryTime: "فوري على الشاشة"
    },
    {
        id: 502,
        categoryId: 5,
        categoryName: "المتاجر الرقمية",
        name: "جوجل بلاي $10 (Google Play US)",
        price: 10.50,
        oldPrice: 12.00,
        image: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=500&auto=format&fit=crop&q=60",
        badge: "كود كارت",
        inputLabel: "رقم الهاتف للتأكيد",
        inputPlaceholder: "أدخل رقم الهاتف...",
        deliveryTime: "فوري"
    },
    {
        id: 601,
        categoryId: 6,
        categoryName: "شحن الخطوط",
        name: "شحن رصيد سيريتل / إم تي إن",
        price: 5.00,
        oldPrice: 6.00,
        image: "https://images.unsplash.com/photo-1523961131990-5ea7c61b2107?w=500&auto=format&fit=crop&q=60",
        badge: "فوري 24/7",
        inputLabel: "رقم الخط (09xxxxxxxx)",
        inputPlaceholder: "أدخل رقم الخط المحلي...",
        deliveryTime: "أقل من دقيقة"
    },
    {
        id: 701,
        categoryId: 7,
        categoryName: "تطبيقات المشاهدة",
        name: "اشتراك شاهد VIP رياضة (30 يوم)",
        price: 8.99,
        oldPrice: 11.00,
        image: "https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?w=500&auto=format&fit=crop&q=60",
        badge: "ضمان HAGAATY",
        inputLabel: "البريد الإلكتروني للتفعيل",
        inputPlaceholder: "أدخل إيميل التفعيل...",
        deliveryTime: "1 - 10 دقائق"
    },
    {
        id: 702,
        categoryId: 7,
        categoryName: "تطبيقات المشاهدة",
        name: "نتفلكس Netflix Premium Ultra HD (شهر)",
        price: 6.50,
        oldPrice: 9.00,
        image: "https://images.unsplash.com/photo-1522869635100-9f4c5e86aa37?w=500&auto=format&fit=crop&q=60",
        badge: "بروفايل خاص + PIN",
        inputLabel: "رقم الواتساب لاستلام بيانات الدخول",
        inputPlaceholder: "أدخل رقم الواتساب...",
        deliveryTime: "فوري"
    },
    {
        id: 1901,
        categoryId: 19,
        categoryName: "تفعيل الأرقام",
        name: "رقم وهمي أمريكي للواتساب (USA Virtual SMS)",
        price: 2.50,
        oldPrice: 4.00,
        image: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=500&auto=format&fit=crop&q=60",
        badge: "كود وصول فوري",
        inputLabel: "ملاحظات وتحديد التطبيق (واتساب/تليجرام)",
        inputPlaceholder: "اختر التطبيق المطلوب...",
        deliveryTime: "تلقائي فوري"
    },
    {
        id: 2001,
        categoryId: 20,
        categoryName: "الحوالات المكتبية والشام كاش",
        name: "تحويل شام كاش (Sham Cash Transfer)",
        price: 10.00,
        oldPrice: 10.00,
        image: "https://images.unsplash.com/photo-1580519542036-c47de6196ba5?w=500&auto=format&fit=crop&q=60",
        badge: "إيداع فوري",
        inputLabel: "رقم محفظة الشام كاش أو رقم المستلم",
        inputPlaceholder: "أدخل رقم المحفظة...",
        deliveryTime: "فوري"
    },
    {
        id: 3701,
        categoryId: 37,
        categoryName: "السوشل ميديا",
        name: "تليجرام - 1000 أعضاء قناة / جروب",
        price: 3.99,
        oldPrice: 6.00,
        image: "https://images.unsplash.com/photo-1614680376593-902f749f7edc?w=500&auto=format&fit=crop&q=60",
        badge: "سرعة فائقة",
        inputLabel: "رابط القناة أو المجموعه (Public Link)",
        inputPlaceholder: "https://t.me/yourchannel",
        deliveryTime: "بدء فوري"
    },
    {
        id: 3702,
        categoryId: 37,
        categoryName: "السوشل ميديا",
        name: "إنستغرام - 5000 متابع حقيقي مع ضمان النقص",
        price: 7.99,
        oldPrice: 12.00,
        image: "https://images.unsplash.com/photo-1611262588024-d12430b98920?w=500&auto=format&fit=crop&q=60",
        badge: "ضمان 30 يوم",
        inputLabel: "رابط الحساب أو اسم المستخدم (Public Profile)",
        inputPlaceholder: "https://instagram.com/username",
        deliveryTime: "خلال دقائق"
    }
];

const CATEGORIES_LIST = [
    { id: 0, name: "الكل", icon: "fa-th-large", count: 16 },
    { id: 1, name: "قسم شحن التطبيقات", icon: "fa-mobile-alt", count: 2 },
    { id: 2, name: "قسم شحن الألعاب", icon: "fa-gamepad", count: 3 },
    { id: 4, name: "قسم الدفع الإلكتروني", icon: "fa-credit-card", count: 2 },
    { id: 5, name: "قسم المتاجر الرقمية", icon: "fa-store", count: 2 },
    { id: 6, name: "قسم شحن الخطوط", icon: "fa-sim-card", count: 1 },
    { id: 7, name: "قسم تطبيقات المشاهدة", icon: "fa-tv", count: 2 },
    { id: 19, name: "قسم تفعيل الأرقام", icon: "fa-sms", count: 1 },
    { id: 20, name: "قسم الشام كاش والحوالات", icon: "fa-money-bill-wave", count: 1 },
    { id: 37, name: "قسم السوشل ميديا", icon: "fa-share-alt", count: 2 }
];
